---
title: "functions"
author: "Hena Ramay"
date: '2020-05-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r function}
# tryting to understand a function

print_vecs<-function(y){
  if(is.vector(y)){
  y=y+30
  } else print("This is not a vector!!")
}

```

```{r select_funs}
counts<-read.table("../../../Intermediate_Rworkshop2020/Notes/data/counts-raw.txt",header = T,sep = "\t")
colnames(counts)

select_first<-function(vec)
{
 return(vec[1])
  
}

select_first(counts$articleType)


```

```{r apply}
m1 <- matrix(C<-(1:10),nrow=5, ncol=6)
apply(m1,MARGIN = 1,FUN = sum)

pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")

split_list<-strsplit(pioneers,split = ":")

#list
lapply(split_list,tolower)
#vector
lapply(pioneers,tolower)

lapply(split_list,select_first)

apply(X = m1,MARGIN = 1,FUN = select_first)

apply(X=m1,MARGIN = 2,FUN = function(x){
  x[1]})

# sapply

temp=list(c(1,3,4,4,6),c(3,4,6,8,9))

extremes <- function(x) {
  c(min = min(x), max = max(x))
}

sapply(temp,extremes)

```