# Project

## Setup
Please download the data folder from <a href="https://www.dropbox.com/sh/qghmd34hekp1pb9/AAB2cnKXcoYmQbx6Xtuws8Zwa?dl=0">Dropbox</a>



## Task 1
1. Create a new R Project for this case study. 
2. Create a new Rmd file to complete your project.
3. Change the auther name of the .Rmd file to your name and add today's date.
4. Read in all the files in the data folder into single dataframe. Hint: Use for loops to read in all the files.Functions that can be helpful : list.files,read_csv,rbind,data.frame(NULL)

<!-- df <- data.frame(NULL) -->
<!-- list.files(path = "../data/",full.names = T)->files -->
<!-- for(i in 1:11) { -->
<!-- +     file_name <-files[i] -->
<!-- +     df_import <- readr::read_csv(file_name, progress = FALSE) -->
<!-- +     df <- rbind(df, df_import) -->
<!-- +     rm(df_import, file_name) -->
<!-- + } -->


## Task 2 

1. Write a function that takes a dataframe as input and if present, converts Monthin to 4 yearly quaters and add an extra column to your dataframe/tibble called Quarters with 4 levels: Q1,Q2,Q3 and, Q4. 
- When Month is Jan-Mar, Quarter = "Q1"
- When Month is Apr-Jun, Quarter = "Q2"
- When Month is Jul-Sep, Quarter = "Q3"
- When Month is Oct-Dec, Quarter = "Q4"

Hint: Use mutate and case_when(), %in% and stop() function
```{r}
m_to_q<-function(dataframe)
{
 if("Month" %in% colnames(dataframe) ){
dataframe <- dataframe %>%
  mutate(Quarter = case_when(
    as.numeric(Month) <= 3 ~ "Q1",
    as.numeric(Month) <= 6 ~ "Q2",
    as.numeric(Month) <= 9 ~ "Q3",
    TRUE                   ~ "Q4"
  ))} else stop("Column Month not found")
return(dataframe)
}
```
## Task 3

1. Generate a bar plot that shows the number of transactions of each card type per quarter. (The card type is called `Factor_C`).
2. Place the legend at the top of the plot. 
3. Remove the x axis labels and tick marks.
4. Colour the card types using a palette of your choice from the RColorBrewer package.


## Task 4

1. Use the `colorRampPalette()` function to generate a colour ramp between any two colours.
2. Plot the distribution (ie. histogram) of Account ID for each quarter.
3. Add a density line.
4. Remove the legend.
5. Plot the density lines only for Account ID for each month on the same plot.

## Task 5

1. Use the dplyr functions to generate a dataframe containing the proportion of Approved and Declined transactions for each card type.
2. Generate a bar plot showing the proportion for each card type.
3. Flip the coordinates so that each card type is a row. 

## Task 6

Generate an html report of all the above tasks using R Markdown. Use [this file](data/case_study_theme.html) as a guide.









